name: "π¨ Design μ‘μ—…"
description: "λ””μμΈ μ‘μ—… μƒμ„±"
labels: ["team: Design"]
body:
  - type: textarea
    id: description
    attributes:
      label: μ‘μ—… λ‚΄μ©
      placeholder: "μ‘μ—… λ‚΄μ©μ„ μƒμ„Έν μ μ–΄μ£Όμ„Έμ”"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: μ°μ„ μμ„
      options:
        - λ†’μ
        - μ¤‘κ°„
        - λ‚®μ
    validations:
      required: true
