name: "π¨ Design μ‘μ—…"
description: "λ””μμΈ ν€ μ‘μ—… μ”μ²­"
labels: ["team: Design"]
body:
  - type: input
    id: title
    attributes:
      label: μ‘μ—… μ λ©
      placeholder: "μ: λ©”μΈ νμ΄μ§€ UI λ””μμΈ"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: μ‘μ—… λ‚΄μ©
      placeholder: "μ‘μ—… λ‚΄μ©μ„ μƒμ„Έν μ μ–΄μ£Όμ„Έμ”"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: μ°μ„ μμ„
      options:
        - λ†’μ
        - μ¤‘κ°„
        - λ‚®μ
    validations:
      required: true
