name: "π’΅ PM μ‘μ—…"
description: "PM μ‘μ—… μƒμ„±"
labels: ["team: PM"]
body:
  - type: input
    id: title
    attributes:
      label: μ‘μ—… λ‚΄μ©
      placeholder: "μ‘μ—… λ‚΄μ©μ„ μƒμ„Έν μ μ–΄μ£Όμ„Έμ”."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: μ°μ„ μμ„
      options:
        - λ†’μ
        - μ¤‘κ°„
        - λ‚®μ
    validations:
      required: true
